---
title: "Making a single metadata and tpm file for all samples"
output: html_document
date: "2025-02-18"
---

# Set up
```{r}
rm(list=ls())
library(ggplot2)
library(tidyr)
library(tidyverse)
library(WGCNA)
library(pheatmap)
library(clusterProfiler)
library(org.Hs.eg.db)
```

# Metadata
### Deceased
```{r}
Meta_Deceased_1<-read.csv("/Users/alinaklineschoder/Downloads/Clarava_validation_122samples_annotations_pred_longterm_outcomes_ryan_reject.csv")%>%
  mutate(Sample_ID=Sequencing_Sample_ID,reject=ryan_reject)%>%
  dplyr::select(reject,Sample_ID,MM_Rejection_Type,Subject,Donor_Vital)%>%
  mutate(Use="Validation",Draw=1)

Meta_Deceased_2<-read.csv("/Users/alinaklineschoder/Downloads/Clarava_deceased_donor_training_5_Annotations_Allinclusive_ar_WithBinaryReject_ar_ryan_reject.csv")%>%
  mutate(Sample_ID=Sample_ID,reject=ryan_reject,Donor_Vital=DONOR_STATUS)%>%
  dplyr::select(reject,Sample_ID,MM_Rejection_Type,Subject,Donor_Vital)%>%
  mutate(Use="Training",Draw=1)
Meta_Deceased<-bind_rows(Meta_Deceased_1,Meta_Deceased_2)
```

### Alive
```{r}
Meta_Alive<-read.csv("/Users/alinaklineschoder/Desktop/LD_Meta.csv")%>%
  mutate(Draw=1)
```

### Meta Draw 2
```{r}
Meta_Draw2<-read.csv("/Users/alinaklineschoder/Downloads/Clarava_22Rejects_postTX_PAXg_BX(Sheet1).csv")%>%
  filter(!is.na(Verici.ID))%>%
  filter(Verici.ID!="")%>%
  mutate(Sample_ID=Verici.ID)%>%
  mutate(Draw=2)
```


## All
```{r}
AllMeta<-bind_rows(Meta_Deceased,Meta_Alive)

AllMeta<-bind_rows(AllMeta,Meta_Draw2)
AllMeta$Sample_ID<-gsub("-","\\.",AllMeta$Sample_ID)

```


## TPM
```{r}
library(tidyverse)
TPM_1<-read.csv("/Users/alinaklineschoder/Downloads/CT1_Expanded_validation_157_TPM.csv")%>%
  dplyr::rename(Gene=GENE)
TPM1<-read.csv("/Users/alinaklineschoder/Downloads/CT1_Stratified_Validation_TPM.csv")%>%
  dplyr::rename(Gene=GENE)
TPM2<-read.csv("/Users/alinaklineschoder/Downloads/CT1_Stratified_Training_TPM(in).csv")

Counts_Train<-read.csv("/Users/alinaklineschoder/Downloads/CT1_Stratified_Validation_TPM_122samples(in).csv")%>%
  dplyr::rename(Gene=X)

tb<-read_tsv(file = "/Users/alinaklineschoder/Downloads/NextSeq2000-VPV3-MissedSamples-Clarava2_clarava_final_gene_matrix.tsv")%>%
  dplyr::rename(Gene=GENE)
colnames(tb)<-gsub("CT1-P-0415-RL-VL00017-CT1-CTOT-RQ-VPV3_S4_L001_R1_001_STAR_Aligned\\.","CT1\\.P\\.0415\\.RL\\.VL00017\\.CT1\\.CTOT\\.RQ\\.VPV3",colnames(tb))

tb2<-read_tsv(file="/Users/alinaklineschoder/Downloads/NextSeq2000__2023-04-05_VL00026-CT1-TNPT4_RQ_ClaravaOnly_clarava_final_gene_matrix.tsv")%>%
  dplyr::rename(Gene=GENE)%>%
  dplyr::select(Gene,`VL00026-CT1-TNPT4-RQ-RL-CT1-P-0273_S21_L001_R1_001_STAR_Aligned.`)

colnames(tb2)<-c("Gene","VL00026.CT1.TNPT4.RQ.RL.CT1.P.0273")

Counts_LD<-read.csv("/Users/alinaklineschoder/Desktop/LD_Counts.csv")%>%
  dplyr::select(-c(X))

Counts_2nd<-read.csv("/Users/alinaklineschoder/Desktop/LivingDonor_iSort_2ndDraw_TPM.csv")

AllCounts<-TPM_1%>%
  left_join(TPM1)%>%
  left_join(TPM2)%>%
  left_join(Counts_Train)%>%
  left_join(tb)%>%
  left_join(tb2)%>%
  left_join(Counts_LD)%>%
  left_join(Counts_2nd)

```

# Ensuring Alignment
```{r}
AllCounts_Filtered<-AllCounts[,c("Gene",setdiff(AllMeta$Sample_ID,"CT1.P.0712"))]
AllMeta<-AllMeta%>%
  filter(Sample_ID!="CT1.P.0712")
```

## iSort Results
```{r}
LD<-read.table("/Users/alinaklineschoder/Downloads/jobresult76/iSort_job76-031925-200003_Relative_AdjustedB.txt",header = T)%>%
  mutate(Sample_ID=Mixture)%>%
  dplyr::select(-c(Mixture,P.value,Correlation,RMSE))

LD$Sample_ID<-gsub("-","\\.",LD$Sample_ID)

DD <- read.table("/Users/alinaklineschoder/Downloads/iSort_job63-121324-160003_Relative_AdjustedB.txt",header = T)%>%
  mutate(Sample_ID=Mixture)%>%
  dplyr::select(-c(Mixture,P.value,Correlation,RMSE))

DD$Sample_ID<-gsub("-","\\.",DD$Sample_ID)

Draw2<-read.table("/Users/alinaklineschoder/Downloads/jobresult77/iSort_job77-032125-133002_Relative_AdjustedB.txt",header = T)%>%
  mutate(Sample_ID=Mixture)%>%
  dplyr::select(-c(Mixture,P.value,Correlation,RMSE))

AlliSort<-bind_rows(LD,DD,Draw2)
colnames(AlliSort)<-gsub("\\.","_",colnames(AlliSort))
AlliSort$Sample_ID<-gsub("-","\\.",AlliSort$Sample_ID)

```


# Saving Everything
```{r}
write.csv(AlliSort,"/Users/alinaklineschoder/Desktop/Data/Clarava_iSort.csv")
write.csv(AllMeta,"/Users/alinaklineschoder/Desktop/Data/Clarava_Meta.csv")
write.csv(AllCounts_Filtered,"/Users/alinaklineschoder/Desktop/Data/Clarava_TPM.csv")
```