---
title: "PlotsForPoster"
output: html_document
date: "2025-02-18"
---

# Set up
```{r}
rm(list=ls())
library(ggplot2)
library(tidyr)
library(tidyverse)
library(WGCNA)
library(pheatmap)
library(clusterProfiler)
library(org.Hs.eg.db)
source("~/Documents/Projects/clarava_manuscript_2025/WGNCA/WGNCA_Helper.R")
```

# Loading in TPM and Meta
```{r}
AllMeta<-read.csv("/Users/alinaklineschoder/Desktop/Data/Clarava_Meta.csv")%>%
  column_to_rownames(var="Sample_ID")
AlliSort<-read.csv("/Users/alinaklineschoder/Desktop/Data/Clarava_iSort.csv")%>%
  column_to_rownames(var="Sample_ID")
AllTPM<-read.csv("/Users/alinaklineschoder/Desktop/Data/Clarava_TPM.csv")%>%
  column_to_rownames(var="Gene")%>%
  dplyr::select(-c(X))
```

# All Data

# Pre-process TPM
```{r}
tpm_data <- t(AllTPM)
tpm_data <- tpm_data[,apply(tpm_data, 2, var) > 0.1]
log_tpm_data <- log2(tpm_data + 1)
gsg = goodSamplesGenes(log_tpm_data, verbose = 3)
datExpr <- log_tpm_data[gsg$goodSamples,gsg$goodGenes]
```

#Soft Threshold Selection

```{r}
powers <- c(1:10, seq(from=12, to=30, by=2))
sft <- pickSoftThreshold(datExpr, corFnc="bicor", corOptions=list(maxPOutliers=0.1), networkType="signed hybrid", powerVector=powers)

# Plot soft-threshold results
par(mfrow = c(1,2))
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3]) * sft$fitIndices[,2],
     xlab = "Soft Threshold (power)", ylab = "Scale-Free Topology Fit", type = "o",
     main = "Scale Independence")
abline(h = 0.9, col = "red")

plot(sft$fitIndices[,1], sft$fitIndices[,5], type = "o",
     xlab = "Soft Threshold (power)", ylab = "Mean Connectivity",
     main = "Mean Connectivity")

# Select best power
softPower <- sft$powerEstimate
softPower <- 5
```

#Network Construction & Module Detection
```{r}
net <- blockwiseModules(datExpr, power=softPower, 
                        TOMType="signed", minModuleSize=30,
                        reassignThreshold=0, mergeCutHeight=0.25,
                        numericLabels=TRUE, pamRespectsDendro=FALSE,
                        networkType="signed hybrid", corType="bicor",
                        maxPOutliers=0.1, verbose=5)
# Convert module labels to colors
moduleColors <- labels2colors(net$colors)

# Plot gene dendrogram with module colors
plotDendroAndColors(net$dendrograms[[1]], moduleColors[net$blockGenes[[1]]], "Module Colors",
                    dendroLabels=FALSE, hang=0.03, addGuide=TRUE, guideHang=0.05)
```

#Module Eigengene Computation
```{r}
MEs0 <- moduleEigengenes(datExpr, moduleColors)$eigengenes
MEs <- orderMEs(MEs0)

# Cluster module eigengenes
METree <- hclust(dist(MEs), method = "average")
plot(METree, main = "Clustering of Module Eigengenes", xlab = "", sub = "")
```

#Module-Trait Associations
```{r}
# Correlate module eigengenes with immune cell fractions
broad_cells_of_interest <- c("Neutrophils", "Monocytes", "Dendritic_cells_activated", "T_cells_gamma_delta")
isort_results_val <- AlliSort[,broad_cells_of_interest]

common_samples <- intersect(rownames(MEs), rownames(isort_results_val))
MEs <- MEs[common_samples,]
isort_results_val <- isort_results_val[common_samples,]

module_trait_cor <- cor(MEs, isort_results_val, use = "p")
module_trait_pval <- corPvalueStudent(module_trait_cor, nSamples = nrow(MEs))

# Plot heatmap
pheatmap(module_trait_cor, display_numbers = TRUE, cluster_rows = TRUE, cluster_cols = TRUE)
```

#Hub Gene Identification
```{r}
# Compute module membership (MM) and gene significance (GS)
geneModuleMembership <- cor(datExpr, MEs, use="p")
MMPvalue <- corPvalueStudent(as.matrix(geneModuleMembership), nSamples = nrow(MEs))

# Identify top hub genes in significant modules
topModules <- rownames(module_trait_pval)[apply(module_trait_pval, 1, function(x) any(x < 0.05))]

hubGenes <- list()

for (module in topModules) {
    moduleGenes <- moduleColors == module
    hubGenes[[module]] <- names(sort(abs(geneModuleMembership[moduleGenes, module]), decreasing = TRUE)[1:10])
}

# Print top hub genes
print(hubGenes)
```

#Gene Set Overlap with Known Panels
```{r}
paper_genes <- c("ENSG00000119711","ENSG00000159363", "ENSG00000100554", "ENSG00000123838", 
  "ENSG00000179388", "ENSG00000135862", "ENSG00000164077", "ENSG00000178802", 
  "ENSG00000196586", "ENSG00000099795", "ENSG00000165609", "ENSG00000157911", 
  "ENSG00000184990", "ENSG00000198740", "ENSG00000176083", "ENSG00000125434", 
  "ENSG00000105072", "ENSG00000182795", "ENSG00000213563", "ENSG00000167775", 
  "ENSG00000102805", "ENSG00000178149", "ENSG00000176845", "ENSG00000148459", 
  "ENSG00000108352", "ENSG00000185187", "ENSG00000130511", "ENSG00000198673", 
  "ENSG00000166848")


for (module in names(hubGenes)) {
    overlap <- length(intersect(hubGenes[[module]], paper_genes))
    cat("Module", module, "overlaps with", overlap, "genes from the paper panel\n")
}

```

#Visualization: Module Membership vs. Gene Significance
```{r}
for (module in topModules) {
    moduleGenes <- moduleColors == module
    verboseScatterplot(abs(geneModuleMembership[moduleGenes, module]),
                       abs(module_trait_cor[module,]),
                       xlab=paste("Module Membership in", module, "module"),
                       ylab="Gene significance for trait",
                       main=paste("Module membership vs. gene significance"))
}

```


