---
title: "PlotsForPoster"
output: html_document
date: "2025-02-18"
---

# Set up
```{r}
rm(list=ls())
library(pROC)
library(ggplot2)
library(tidyr)
library(tidyverse)
Palette2<-c("#141C52","#F23F1C")
names(Palette2)<-c("NoReject","Reject")
```

```{r}
Data<-read.csv("/Users/alinaklineschoder/Downloads/Clarava_validation_122samples_annotations_pred_longterm_outcomes_ryan_reject.csv")%>%
  mutate(Subject=Sequencing_Sample_ID,reject=ryan_reject)%>%
  dplyr::select(reject,Subject,MM_Rejection_Type,Subject)

Data2<-read.csv("/Users/alinaklineschoder/Downloads/Clarava_deceased_donor_training_5_Annotations_Allinclusive_ar_WithBinaryReject_ar_ryan_reject.csv")%>%
  mutate(Subject=Sample_ID,reject=ryan_reject)%>%
  dplyr::select(reject,Subject,MM_Rejection_Type)
Data<-bind_rows(Data,Data2)

typs<-unique(Data$MM_Rejection_Type)
Mixed<-setdiff(typs[grepl("ABMR",typs)],"ABMR")
TCMR<-setdiff(typs[!grepl("ABMR",typs)],"")

Data$Group2<-"NoReject"
Data[Data$MM_Rejection_Type%in%Mixed,"Group2"]<-"Mixed ABMR/TCMR"
Data[Data$MM_Rejection_Type%in%TCMR,"Group2"]<-"TCMR"
Data[Data$MM_Rejection_Type=="ABMR","Group2"]<-"ABMR"
Data$Group2<-factor(Data$Group2,levels = c("ABMR","Mixed ABMR/TCMR","TCMR","NoReject"))
isort_results_val <- read.table("/Users/alinaklineschoder/Downloads/iSort_job63-121324-160003_Relative_AdjustedB.txt",header = T)%>%
  mutate(Subject=Mixture)%>%
  dplyr::select(-c(Mixture,P.value,Correlation,RMSE))
colnames(isort_results_val) <- gsub("\\.","_",colnames(isort_results_val))
```

```{r}
Long <- Data %>%
  left_join(isort_results_val) %>%
  pivot_longer(cols=setdiff(colnames(.), c("Subject", "reject","MM_Rejection_Type","Group","Group2"))) %>%
  group_by(name) %>%
  mutate(value = (value - min(value, na.rm = TRUE)) / (max(value, na.rm = TRUE) - min(value, na.rm = TRUE)))

Long$Broad<-"Other"
Long$Broad[Long$name%in%c("B_cells_naive","B_cells_memory")]<-"B Cells"
Long$Broad[Long$name%in%c("T_cells_CD4_memory_activated","T_cells_CD4_memory_resting","T_cells_CD4_naive","T_cells_follicular_helper","T_cells_regulatory__Tregs_","T_cells_gamma_delta","T_cells_CD8")]<-"T-Cells"

Long$Broad[Long$name%in%c("NK_cells_resting","NK_cells_activated")]<-"NK Cells"
Long$Broad[Long$name%in%c("Dendritic_cells_resting","Dendritic_cells_activated")]<-"Dendritic Cells"
Long$Broad[Long$name%in%c("Mast_cells_resting","Mast_cells_activated")]<-"Mast Cells"
Long$Broad[Long$name%in%c("Macrophages_M0","Macrophages_M1","Macrophages_M2","Monocytes")]<-"Macrophages/\nMonocytes"

Long$name <- sapply(Long$name, function(d) {
    categorized <- case_when(
      d == "B_cells_naive" ~ "Naive B-Cells",
      d == "B_cells_memory" ~ "Memory B-Cells",
      d == "Plasma_cells" ~ "Plasma Cells",
      d == "T_cells_CD8" ~ "CD8 T-Cells",
      d == "T_cells_CD4_naive" ~ "Naive CD4 T-Cells",
      d == "T_cells_CD4_memory_resting" ~ "CD4 Resting Memory T-Cells",
      d == "T_cells_CD4_memory_activated" ~ "CD4 Activated Memory T-Cells",
      d == "T_cells_follicular_helper" ~ "Follicular Helper T-Cells",
      d == "T_cells_regulatory__Tregs_" ~ "Regulatory T-Cells",
      d == "T_cells_gamma_delta" ~ "Gamma-Delta T-Cells",
      d == "NK_cells_resting" ~ "Resting NK Cells",
      d == "NK_cells_activated" ~ "Activated NK Cells",
      d == "Macrophages_M0" ~ "M0 Macrophages",
      d == "Macrophages_M1" ~ "M1 Macrophages",
      d == "Macrophages_M2" ~ "M2 Macrophages",
      d == "Dendritic_cells_resting" ~ "Resting Dendritic Cells",
      d == "Dendritic_cells_activated" ~ "Activated Dendritic Cells",
      d == "Mast_cells_resting" ~ "Resting Mast Cells",
      d == "Mast_cells_activated" ~ "Activated Mast Cells",
      d == "Monocytes" ~ "Monocytes",
      d == "Eosinophils" ~ "Eosinophils",
      d == "Neutrophils" ~ "Neutrophils",
    )
})



library(ggplot2)
library(dplyr)

# Reorder 'name' by median value
Order <- Long %>%
  group_by(name)%>%
  summarize(med=mean(value))%>%
  arrange(med)%>%
  pull(name)

Long$name<-factor(Long$name,levels=Order)
```

# Version 1
```{r}
ggp<-ggplot(Long, aes(x = name, y = value, color = reject)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(dodge.width = 0.7, jitter.width = 0.1), 
             size = 0.05, alpha = 0.5) +
  ggpubr::stat_compare_means(method = "t.test", label = "p.format", 
                             hide.ns = FALSE, size = 3, hjust = 0.5, vjust = 0.5) +
  theme(legend.position = "top") +
  coord_flip() +
  theme_bw() +
  scale_color_manual(values = Palette2) +
  theme(legend.title = element_blank()) +
  facet_grid(Broad ~ ., scales = "free_y", drop = TRUE, space = "free") +
  theme(strip.background = element_rect(fill = "white"),
        strip.text.y.right = element_text(angle = 0),
        panel.grid = element_blank()) +
  labs(y = "Composition (Min/Max Normalized)") +
  theme(axis.title.y = element_blank())

ggsave(plot = ggp,filename="/Users/alinaklineschoder/Desktop/RvNR.png",width = 10,height = 8)
```

# Version 2
```{r}
# Compute p-values per 'name' within each facet level of Broad
pvals_df <- Long %>%
  group_by(Broad, name) %>%
  summarise(
    pval = tryCatch({
      t.test(value ~ reject)$p.value
    }, error = function(e) NA_real_),
    .groups = "drop"
  ) %>%
  mutate(pval_rounded = ifelse(!is.na(pval), sprintf("p = %.3f", round(pval, 3)), "p = NA"))%>%
  mutate(y_pos=1.1)

# Plot with manual p-values
V2_Colors1<-ggplot(Long, aes(x = name, y = value, color = reject)) +
  geom_boxplot(outlier.shape = NA,linewidth = 0.25) +
  geom_text(data = pvals_df%>%distinct(),
            aes(x = name, y = y_pos, label = pval_rounded),
            inherit.aes = FALSE,
            size = 3, hjust = 0.5) +
  theme(legend.position = "top") +
  coord_flip() +
  theme_bw() +
  scale_color_manual(values = c("#F23F1C","#141C52")) +
  theme(
    legend.title = element_blank(),
    strip.background = element_rect(fill = "white"),
    strip.text.y.right = element_blank(),
    panel.grid = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "top",
    axis.text=element_text(size=12),
    axis.title.x = element_text(size=14)
  ) +
  facet_grid(Broad ~ ., scales = "free_y", drop = TRUE, space = "free") +
  labs(y = "Composition (Min/Max Normalized)")+
  ylim(c(0,1.12))

ggsave("/Users/alinaklineschoder/Desktop/Data/iSort/Reject_BoxPlot_V2_NavyOrange.png",V2_Colors1,dpi = 300,width = 10,height = 7)

# Plot with manual p-values
V2_Colors2<-ggplot(Long, aes(x = name, y = value, color = reject)) +
  geom_boxplot(outlier.shape = NA,linewidth = 0.25) +
  geom_text(data = pvals_df%>%distinct(),
            aes(x = name, y = y_pos, label = pval_rounded),
            inherit.aes = FALSE,
            size = 3, hjust = 0.5) +
  theme(legend.position = "top") +
  coord_flip() +
  theme_bw() +
  scale_color_manual(values = c("#0092E1", "#DA188D")) +
  theme(
    legend.title = element_blank(),
    strip.background = element_rect(fill = "white"),
    strip.text.y.right = element_blank(),
    panel.grid = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "top",
    axis.text=element_text(size=12),
    axis.title.x = element_text(size=14)
  ) +
  facet_grid(Broad ~ ., scales = "free_y", drop = TRUE, space = "free") +
  labs(y = "Composition (Min/Max Normalized)")+
  ylim(c(0,1.12))

ggsave("/Users/alinaklineschoder/Desktop/Data/iSort/Reject_BoxPlot_BluePink.png",V2_Colors2,dpi = 300,width = 8,height = 7)
```

```{r}
# Compute min-max for each group for range bars
summary_df <- Long %>%
  group_by(Broad, name, reject) %>%
  summarise(
    q25 = quantile(value, 0.25, na.rm = TRUE),
    q50 = quantile(value, 0.50, na.rm = TRUE),
    q75 = quantile(value, 0.75, na.rm = TRUE),
    .groups = "drop"
  )

# Compute p-values per 'name' within each facet level of Broad
pvals_df <- Long %>%
  group_by(Broad, name) %>%
  summarise(
    pval = tryCatch({
      t.test(value ~ reject)$p.value
    }, error = function(e) NA_real_),
    .groups = "drop"
  ) %>%
  mutate(pval_rounded = ifelse(!is.na(pval), sprintf("p = %.3f", round(pval, 3)), "p = NA"))%>%
  mutate(y_pos=1.1)


# Plot with manual p-values
V3<-ggplot(Long, aes(x = name, y = value, color = reject)) +
  geom_linerange(data = summary_df,
                 aes(x = name, ymin = q25, ymax = q75, color = reject),
                 position = position_dodge(width = 0.7),
                 size = 0.5,
                 inherit.aes = FALSE) +
  geom_point(data = summary_df,
             aes(x = name, y = q50, color = reject),
             position = position_dodge(width = 0.7),
             size = 2,
             inherit.aes = FALSE) +
  geom_text(data = pvals_df%>%distinct(),
            aes(x = name, y = y_pos, label = pval_rounded),
            inherit.aes = FALSE,
            size = 3, hjust = 0.5) +
  theme(legend.position = "top") +
  coord_flip() +
  theme_bw() +
  scale_color_manual(values = c("#0092E1", "#DA188D")) +
  theme(
    legend.title = element_blank(),
    strip.background = element_rect(fill = "white"),
    strip.text.y.right = element_blank(),
    panel.grid = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "top",
    axis.text=element_text(size=12),
    axis.title.x = element_text(size=14)
  ) +
  facet_grid(Broad ~ ., scales = "free_y", drop = TRUE, space = "free") +
  labs(y = "Composition (Min/Max Normalized)")+
  ylim(c(0,1.12))

ggsave("/Users/alinaklineschoder/Desktop/Data/iSort/Reject_LinePlot_BluePink.png",V3,dpi = 300,width = 8,height = 7)

# Plot with manual p-values
V3B<-ggplot(Long, aes(x = name, y = value, color = reject)) +
  geom_linerange(data = summary_df,
                 aes(x = name, ymin = q25, ymax = q75, color = reject),
                 position = position_dodge(width = 0.7),
                 size = 0.5,
                 inherit.aes = FALSE) +
  geom_point(data = summary_df,
             aes(x = name, y = q50, color = reject),
             position = position_dodge(width = 0.7),
             size = 2,
             inherit.aes = FALSE) +
  geom_text(data = pvals_df%>%distinct(),
            aes(x = name, y = y_pos, label = pval_rounded),
            inherit.aes = FALSE,
            size = 3, hjust = 0.5) +
  theme(legend.position = "top") +
  coord_flip() +
  theme_bw() +
  scale_color_manual(values = c("#F23F1C","#141C52")) +
  theme(
    legend.title = element_blank(),
    strip.background = element_rect(fill = "white"),
    strip.text.y.right = element_blank(),
    panel.grid = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "top",
    axis.text=element_text(size=12),
    axis.title.x = element_text(size=14)
  ) +
  facet_grid(Broad ~ ., scales = "free_y", drop = TRUE, space = "free") +
  labs(y = "Composition (Min/Max Normalized)")+
  ylim(c(0,1.12))

ggsave("/Users/alinaklineschoder/Desktop/Data/iSort/Reject_LinePlot_NavyOrange.png",V3B,dpi = 300,width = 8,height = 7)
```


